In [2]:
import numpy as np
import pandas as pd

In [3]:

train_df = pd.read_csv("train.csv")

In [4]:
train_df

loan_number  amount_borrowed  term  borrower_rate  installment grade  \
0          71418865             5100    36         0.0916       162.56     B   
1          44116029            11775    60         0.1786       298.12     D   
2          30245478            20000    36         0.0839       630.34     A   
3          71673111             6000    36         0.0649       183.87     A   
4          15481006            22500    36         0.0662       690.84     A   
...             ...              ...   ...            ...          ...   ...   
943690     28432727            35000    36         0.1449      1204.57     C   
943691     12616138            21000    36         0.1249       702.43     B   
943692      3016671             8875    36         0.1212       295.29     B   
943693     51908873            12500    36         0.0726       387.46     A   
943694      3351684             8000    36         0.1114       262.45     B   

        origination_date       listing_title  principal_balance  \
0       2016-02-01T00:00         credit_card            1256.87   
1       2015-03-01T00:00  debt_consolidation               0.00   
2       2014-10-01T00:00  debt_consolidation               0.00   
3       2016-02-01T00:00  debt_consolidation               0.00   
4       2014-05-01T00:00  debt_consolidation               0.00   
...                  ...                 ...                ...   
943690  2014-10-01T00:00  debt_consolidation               0.00   
943691  2014-04-01T00:00  debt_consolidation               0.00   
943692  2013-01-01T00:00  debt_consolidation               0.00   
943693  2015-06-01T00:00  debt_consolidation               0.00   
943694  2013-02-01T00:00  debt_consolidation               0.00   

        principal_paid  interest_paid  late_fees_paid last_payment_date  \
0              3843.13         705.95             0.0  2018-06-01T00:00   
1              2356.98        2687.69             0.0  2016-09-01T00:00   
2             20000.00        2668.60             0.0  2017-10-01T00:00   
3              6000.00         346.34             0.0  2017-02-01T00:00   
4             22500.00        1240.16             0.0  2015-12-01T00:00   
...                ...            ...             ...               ...   
943690         8258.31        3787.39             0.0  2015-08-01T00:00   
943691        21000.00        1996.93             0.0  2015-02-01T00:00   
943692         8875.00        1427.85             0.0  2014-11-01T00:00   
943693        12500.00          52.94             0.0  2015-07-01T00:00   
943694         8000.00        1447.79             0.0  2016-02-01T00:00   

       next_payment_due_date  days_past_due loan_status_description  \
0           2018-07-01T00:00             60                 CURRENT   
1           2016-10-01T00:00            698               CHARGEOFF   
2           2017-11-01T00:00              0               COMPLETED   
3           2017-03-01T00:00              0               COMPLETED   
4           2016-01-01T00:00              0               COMPLETED   
...                      ...            ...                     ...   
943690      2015-09-01T00:00           1094               CHARGEOFF   
943691      2015-03-01T00:00              0               COMPLETED   
943692      2014-12-01T00:00              0               COMPLETED   
943693      2015-08-01T00:00              0               COMPLETED   
943694      2016-03-01T00:00              0               COMPLETED   

           data_source  
0       'Lending Club'  
1       'Lending Club'  
2       'Lending Club'  
3       'Lending Club'  
4       'Lending Club'  
...                ...  
943690  'Lending Club'  
943691  'Lending Club'  
943692  'Lending Club'  
943693  'Lending Club'  
943694  'Lending Club'  

[943695 rows x 17 columns]

In [5]:
dates = ['origination_date','last_payment_date','next_payment_due_date']
for col in dates:
    train_df[col] = pd.to_datetime(train_df[col])


In [6]:
train_df['org_date_month'] = train_df['origination_date'].dt.month

In [7]:
train_df['org_date_year'] = train_df['origination_date'].dt.year

In [8]:
train_df['lst_payment_month'] = train_df['last_payment_date'].dt.month
train_df['lst_payment_year'] = train_df['last_payment_date'].dt.year


In [9]:
train_df['pay_period']=train_df['last_payment_date']-train_df['origination_date']

In [10]:
train_df = train_df.drop(['origination_date','last_payment_date','next_payment_due_date'],axis=1)

In [11]:
train_df

loan_number  amount_borrowed  term  borrower_rate  installment grade  \
0          71418865             5100    36         0.0916       162.56     B   
1          44116029            11775    60         0.1786       298.12     D   
2          30245478            20000    36         0.0839       630.34     A   
3          71673111             6000    36         0.0649       183.87     A   
4          15481006            22500    36         0.0662       690.84     A   
...             ...              ...   ...            ...          ...   ...   
943690     28432727            35000    36         0.1449      1204.57     C   
943691     12616138            21000    36         0.1249       702.43     B   
943692      3016671             8875    36         0.1212       295.29     B   
943693     51908873            12500    36         0.0726       387.46     A   
943694      3351684             8000    36         0.1114       262.45     B   

             listing_title  principal_balance  principal_paid  interest_paid  \
0              credit_card            1256.87         3843.13         705.95   
1       debt_consolidation               0.00         2356.98        2687.69   
2       debt_consolidation               0.00        20000.00        2668.60   
3       debt_consolidation               0.00         6000.00         346.34   
4       debt_consolidation               0.00        22500.00        1240.16   
...                    ...                ...             ...            ...   
943690  debt_consolidation               0.00         8258.31        3787.39   
943691  debt_consolidation               0.00        21000.00        1996.93   
943692  debt_consolidation               0.00         8875.00        1427.85   
943693  debt_consolidation               0.00        12500.00          52.94   
943694  debt_consolidation               0.00         8000.00        1447.79   

        late_fees_paid  days_past_due loan_status_description     data_source  \
0                  0.0             60                 CURRENT  'Lending Club'   
1                  0.0            698               CHARGEOFF  'Lending Club'   
2                  0.0              0               COMPLETED  'Lending Club'   
3                  0.0              0               COMPLETED  'Lending Club'   
4                  0.0              0               COMPLETED  'Lending Club'   
...                ...            ...                     ...             ...   
943690             0.0           1094               CHARGEOFF  'Lending Club'   
943691             0.0              0               COMPLETED  'Lending Club'   
943692             0.0              0               COMPLETED  'Lending Club'   
943693             0.0              0               COMPLETED  'Lending Club'   
943694             0.0              0               COMPLETED  'Lending Club'   

        org_date_month  org_date_year  lst_payment_month  lst_payment_year  \
0                    2           2016                  6              2018   
1                    3           2015                  9              2016   
2                   10           2014                 10              2017   
3                    2           2016                  2              2017   
4                    5           2014                 12              2015   
...                ...            ...                ...               ...   
943690              10           2014                  8              2015   
943691               4           2014                  2              2015   
943692               1           2013                 11              2014   
943693               6           2015                  7              2015   
943694               2           2013                  2              2016   

       pay_period  
0        851 days  
1        550 days  
2       1096 days  
3        366 days  
4        579 days  
...           ...  
943690   304 days  
943691   306 day

In [12]:
cols = list(train_df.columns)

In [13]:
re_cols = ['loan_number',
 'amount_borrowed',
 'term',
 'borrower_rate',
 'installment',
 'grade',
 'org_date_month',
 'org_date_year',
 'lst_payment_month',
 'lst_payment_year',
 'pay_period',
 'listing_title',
 'principal_balance',
 'principal_paid',
 'interest_paid',
 'late_fees_paid',
 'days_past_due',
 'loan_status_description',
 'data_source']

In [14]:
train_df = train_df[re_cols]

In [15]:
train_df

loan_number  amount_borrowed  term  borrower_rate  installment grade  \
0          71418865             5100    36         0.0916       162.56     B   
1          44116029            11775    60         0.1786       298.12     D   
2          30245478            20000    36         0.0839       630.34     A   
3          71673111             6000    36         0.0649       183.87     A   
4          15481006            22500    36         0.0662       690.84     A   
...             ...              ...   ...            ...          ...   ...   
943690     28432727            35000    36         0.1449      1204.57     C   
943691     12616138            21000    36         0.1249       702.43     B   
943692      3016671             8875    36         0.1212       295.29     B   
943693     51908873            12500    36         0.0726       387.46     A   
943694      3351684             8000    36         0.1114       262.45     B   

        org_date_month  org_date_year  lst_payment_month  lst_payment_year  \
0                    2           2016                  6              2018   
1                    3           2015                  9              2016   
2                   10           2014                 10              2017   
3                    2           2016                  2              2017   
4                    5           2014                 12              2015   
...                ...            ...                ...               ...   
943690              10           2014                  8              2015   
943691               4           2014                  2              2015   
943692               1           2013                 11              2014   
943693               6           2015                  7              2015   
943694               2           2013                  2              2016   

       pay_period       listing_title  principal_balance  principal_paid  \
0        851 days         credit_card            1256.87         3843.13   
1        550 days  debt_consolidation               0.00         2356.98   
2       1096 days  debt_consolidation               0.00        20000.00   
3        366 days  debt_consolidation               0.00         6000.00   
4        579 days  debt_consolidation               0.00        22500.00   
...           ...                 ...                ...             ...   
943690   304 days  debt_consolidation               0.00         8258.31   
943691   306 days  debt_consolidation               0.00        21000.00   
943692   669 days  debt_consolidation               0.00         8875.00   
943693    30 days  debt_consolidation               0.00        12500.00   
943694  1095 days  debt_consolidation               0.00         8000.00   

        interest_paid  late_fees_paid  days_past_due loan_status_description  \
0              705.95             0.0             60                 CURRENT   
1             2687.69             0.0            698               CHARGEOFF   
2             2668.60             0.0              0               COMPLETED   
3              346.34             0.0              0               COMPLETED   
4             1240.16             0.0              0               COMPLETED   
...               ...             ...            ...                     ...   
943690        3787.39             0.0           1094               CHARGEOFF   
943691        1996.93             0.0              0               COMPLETED   
943692        1427.85             0.0              0               COMPLETED   
943693          52.94             0.0              0               COMPLETED   
943694        1447.79             0.0              0               COMPLETED   

           data_source  
0       'Lending Club'  
1       'Lending Club'  
2       'Lending Club'  
3       'Lending Club'  
4       'Lending Club'  
...                ...  
943690  'Lending Club'  
943691  'Lending Club'  
943692  'Le

In [16]:
train_df = train_df[~train_df['listing_title'].isin(['educational'])]

In [17]:
X = train_df.drop(['loan_status_description','loan_number','data_source','org_date_month','lst_payment_month'],axis=1)
X

amount_borrowed  term  borrower_rate  installment grade  \
0                  5100    36         0.0916       162.56     B   
1                 11775    60         0.1786       298.12     D   
2                 20000    36         0.0839       630.34     A   
3                  6000    36         0.0649       183.87     A   
4                 22500    36         0.0662       690.84     A   
...                 ...   ...            ...          ...   ...   
943690            35000    36         0.1449      1204.57     C   
943691            21000    36         0.1249       702.43     B   
943692             8875    36         0.1212       295.29     B   
943693            12500    36         0.0726       387.46     A   
943694             8000    36         0.1114       262.45     B   

        org_date_year  lst_payment_year pay_period       listing_title  \
0                2016              2018   851 days         credit_card   
1                2015              2016   550 days  debt_consolidation   
2                2014              2017  1096 days  debt_consolidation   
3                2016              2017   366 days  debt_consolidation   
4                2014              2015   579 days  debt_consolidation   
...               ...               ...        ...                 ...   
943690           2014              2015   304 days  debt_consolidation   
943691           2014              2015   306 days  debt_consolidation   
943692           2013              2014   669 days  debt_consolidation   
943693           2015              2015    30 days  debt_consolidation   
943694           2013              2016  1095 days  debt_consolidation   

        principal_balance  principal_paid  interest_paid  late_fees_paid  \
0                 1256.87         3843.13         705.95             0.0   
1                    0.00         2356.98        2687.69             0.0   
2                    0.00        20000.00        2668.60             0.0   
3                    0.00         6000.00         346.34             0.0   
4                    0.00        22500.00        1240.16             0.0   
...                   ...             ...            ...             ...   
943690               0.00         8258.31        3787.39             0.0   
943691               0.00        21000.00        1996.93             0.0   
943692               0.00         8875.00        1427.85             0.0   
943693               0.00        12500.00          52.94             0.0   
943694               0.00         8000.00        1447.79             0.0   

        days_past_due  
0                  60  
1                 698  
2                   0  
3                   0  
4                   0  
...               ...  
943690           1094  
943691              0  
943692              0  
943693              0  
943694              0  

[943694 rows x 14 columns]

In [18]:
X['pay_period'] = X['pay_period'].astype('timedelta64[D]').astype(int)
X

amount_borrowed  term  borrower_rate  installment grade  \
0                  5100    36         0.0916       162.56     B   
1                 11775    60         0.1786       298.12     D   
2                 20000    36         0.0839       630.34     A   
3                  6000    36         0.0649       183.87     A   
4                 22500    36         0.0662       690.84     A   
...                 ...   ...            ...          ...   ...   
943690            35000    36         0.1449      1204.57     C   
943691            21000    36         0.1249       702.43     B   
943692             8875    36         0.1212       295.29     B   
943693            12500    36         0.0726       387.46     A   
943694             8000    36         0.1114       262.45     B   

        org_date_year  lst_payment_year  pay_period       listing_title  \
0                2016              2018         851         credit_card   
1                2015              2016         550  debt_consolidation   
2                2014              2017        1096  debt_consolidation   
3                2016              2017         366  debt_consolidation   
4                2014              2015         579  debt_consolidation   
...               ...               ...         ...                 ...   
943690           2014              2015         304  debt_consolidation   
943691           2014              2015         306  debt_consolidation   
943692           2013              2014         669  debt_consolidation   
943693           2015              2015          30  debt_consolidation   
943694           2013              2016        1095  debt_consolidation   

        principal_balance  principal_paid  interest_paid  late_fees_paid  \
0                 1256.87         3843.13         705.95             0.0   
1                    0.00         2356.98        2687.69             0.0   
2                    0.00        20000.00        2668.60             0.0   
3                    0.00         6000.00         346.34             0.0   
4                    0.00        22500.00        1240.16             0.0   
...                   ...             ...            ...             ...   
943690               0.00         8258.31        3787.39             0.0   
943691               0.00        21000.00        1996.93             0.0   
943692               0.00         8875.00        1427.85             0.0   
943693               0.00        12500.00          52.94             0.0   
943694               0.00         8000.00        1447.79             0.0   

        days_past_due  
0                  60  
1                 698  
2                   0  
3                   0  
4                   0  
...               ...  
943690           1094  
943691              0  
943692              0  
943693              0  
943694              0  

[943694 rows x 14 columns]

In [19]:
object_cols = ['grade', 'listing_title']

In [20]:
from sklearn.preprocessing import OneHotEncoder

# Apply one-hot encoder to each column with categorical data
OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse=False)
OH_cols_train = pd.DataFrame(OH_encoder.fit_transform(X[object_cols]))


# One-hot encoding removed index; put it back
OH_cols_train.index = X.index


# Remove categorical columns (will replace with one-hot encoding)
X = X.drop(object_cols, axis=1)


# Add one-hot encoded columns to numerical features
X = pd.concat([X, OH_cols_train], axis=1)

In [21]:
X

amount_borrowed  term  borrower_rate  installment  org_date_year  \
0                  5100    36         0.0916       162.56           2016   
1                 11775    60         0.1786       298.12           2015   
2                 20000    36         0.0839       630.34           2014   
3                  6000    36         0.0649       183.87           2016   
4                 22500    36         0.0662       690.84           2014   
...                 ...   ...            ...          ...            ...   
943690            35000    36         0.1449      1204.57           2014   
943691            21000    36         0.1249       702.43           2014   
943692             8875    36         0.1212       295.29           2013   
943693            12500    36         0.0726       387.46           2015   
943694             8000    36         0.1114       262.45           2013   

        lst_payment_year  pay_period  principal_balance  principal_paid  \
0                   2018         851            1256.87         3843.13   
1                   2016         550               0.00         2356.98   
2                   2017        1096               0.00        20000.00   
3                   2017         366               0.00         6000.00   
4                   2015         579               0.00        22500.00   
...                  ...         ...                ...             ...   
943690              2015         304               0.00         8258.31   
943691              2015         306               0.00        21000.00   
943692              2014         669               0.00         8875.00   
943693              2015          30               0.00        12500.00   
943694              2016        1095               0.00         8000.00   

        interest_paid  ...   10   11   12   13   14   15   16   17   18   19  
0              705.95  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1             2687.69  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2             2668.60  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3              346.34  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4             1240.16  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...               ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
943690        3787.39  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
943691        1996.93  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
943692        1427.85  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
943693          52.94  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
943694        1447.79  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[943694 rows x 32 columns]

In [22]:
X.columns

Index([  'amount_borrowed',              'term',     'borrower_rate',
             'installment',     'org_date_year',  'lst_payment_year',
              'pay_period', 'principal_balance',    'principal_paid',
           'interest_paid',    'late_fees_paid',     'days_past_due',
                         0,                   1,                   2,
                         3,                   4,                   5,
                         6,                   7,                   8,
                         9,                  10,                  11,
                        12,                  13,                  14,
                        15,                  16,                  17,
                        18,                  19],
      dtype='object')

In [23]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
y = le.fit_transform(train_df["loan_status_description"])

In [24]:
y

array([2, 0, 1, ..., 1, 1, 1])

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=42)
X_train.shape, X_test.shape

((660585, 32), (283109, 32))

In [26]:
from imblearn.over_sampling import SMOTE
oversample = SMOTE()
X_resampled, y_resampled = oversample.fit_resample(X_train, y_train)

c:\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [27]:
X_resampled

amount_borrowed  term  borrower_rate  installment  org_date_year  \
0                  20000    36       0.109900   654.680000           2013   
1                  17825    36       0.199700   662.170000           2014   
2                   8500    36       0.116700   280.990000           2014   
3                  19500    60       0.091700   406.400000           2015   
4                  16000    60       0.089900   332.060000           2016   
...                  ...   ...            ...          ...            ...   
1607099            12600    60       0.174146   316.009557           2015   
1607100            20098    60       0.108934   435.985248           2015   
1607101            26524    36       0.134709   900.434888           2015   
1607102             5000    36       0.086332   158.211390           2015   
1607103             4978    36       0.119360   165.211751           2016   

         lst_payment_year  pay_period  principal_balance  principal_paid  \
0                    2016         852           0.000000    14956.480000   
1                    2014         243           0.000000    17825.000000   
2                    2017        1096           0.000000     8500.000000   
3                    2018        1004        9880.790000     9619.210000   
4                    2017         365           0.000000    16000.000000   
...                   ...         ...                ...             ...   
1607099              2018         941        7464.724151     5135.275849   
1607100              2018         712       13535.670918     6562.652647   
1607101              2018         860        7360.416469    19164.288696   
1607102              2018         767        1786.185114     3213.814886   
1607103              2018         814        2144.599706     2833.627590   

         interest_paid  ...        10   11        12   13   14   15   16  \
0          3408.890000  ...  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0   
1          2196.990000  ...  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0   
2          1615.370000  ...  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0   
3          3812.570000  ...  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0   
4          1369.490000  ...  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0   
...                ...  ...       ...  ...       ...  ...  ...  ...  ...   
1607099    4607.554818  ...  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0   
1607100    3612.953736  ...  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0   
1607101    5506.147498  ...  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0   
1607102     616.150538  ...  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0   
1607103     851.606873  ...  0.956455  0.0  0.043545  0.0  0.0  0.0  0.0   

               17   18   19  
0        0.000000  0.0  0.0  
1        0.000000  0.0  0.0  
2        0.000000  0.0  0.0  
3        0.000000  0.0  0.0  
4        0.000000  0.0  0.0  
...           ...  ...  ...  
1607099  0.000000  0.0  0.0  
1607100  0.000000  0.0  0.0  
1607101  0.000000  0.0  0.0  
1607102  0.175872  0.0  0.0  
1607103  0.000000  0.0  0.0  

[1607104 rows x 32 columns]

In [28]:
y_resampled

array([0, 1, 1, ..., 3, 3, 3])

In [29]:
y_df = pd.DataFrame({'loan_status_discription':y_resampled})
y_df.value_counts()

loan_status_discription
0                          401776
1                          401776
2                          401776
3                          401776
dtype: int64

In [89]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [30]:
from catboost import CatBoostClassifier

cat_clf = CatBoostClassifier()
cat_clf.fit(X_resampled,y_resampled)



Learning rate set to 0.115301
0:	learn: 1.0669829	total: 632ms	remaining: 10m 30s
1:	learn: 0.8650626	total: 1.09s	remaining: 9m 5s
2:	learn: 0.7183907	total: 1.58s	remaining: 8m 45s
3:	learn: 0.6061216	total: 2.09s	remaining: 8m 40s
4:	learn: 0.5175296	total: 2.58s	remaining: 8m 33s
5:	learn: 0.4457157	total: 3.06s	remaining: 8m 26s
6:	learn: 0.3861634	total: 3.57s	remaining: 8m 26s
7:	learn: 0.3362799	total: 4.07s	remaining: 8m 24s
8:	learn: 0.2942481	total: 4.58s	remaining: 8m 24s
9:	learn: 0.2585143	total: 5.04s	remaining: 8m 19s
10:	learn: 0.2277337	total: 5.53s	remaining: 8m 17s
11:	learn: 0.2010897	total: 6.02s	remaining: 8m 16s
12:	learn: 0.1780095	total: 6.5s	remaining: 8m 13s
13:	learn: 0.1580482	total: 7s	remaining: 8m 13s
14:	learn: 0.1405157	total: 7.48s	remaining: 8m 11s
15:	learn: 0.1251217	total: 7.96s	remaining: 8m 9s
16:	learn: 0.1118608	total: 8.46s	remaining: 8m 9s
17:	learn: 0.0999673	total: 8.94s	remaining: 8m 7s
18:	learn: 0.0895006	total: 9.42s	remaining: 8m 6s


In [31]:
print(accuracy_score(cat_clf.predict(X_test),y_test))
print(confusion_matrix(cat_clf.predict(X_test),y_test))
print(classification_report(cat_clf.predict(X_test),y_test))

0.9994348466491705
[[ 44508      0      7      0]
 [     0 172246      0      0]
 [     9      0  66103     32]
 [     0      0    112     92]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     44515
           1       1.00      1.00      1.00    172246
           2       1.00      1.00      1.00     66144
           3       0.74      0.45      0.56       204

    accuracy                           1.00    283109
   macro avg       0.93      0.86      0.89    283109
weighted avg       1.00      1.00      1.00    283109



In [87]:
import lightgbm as lgb
lgbm_clf = lgb.LGBMClassifier()
lgbm_clf.fit(X_resampled, y_resampled)

LGBMClassifier()

In [88]:
print(accuracy_score(lgbm_clf.predict(X_test),y_test))
print(confusion_matrix(lgbm_clf.predict(X_test),y_test))
print(classification_report(lgbm_clf.predict(X_test),y_test))

0.9995125552349096
[[ 44515      0      2      1]
 [     0 172246      0      0]
 [     2      0  66139     52]
 [     0      0     81     71]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     44518
           1       1.00      1.00      1.00    172246
           2       1.00      1.00      1.00     66193
           3       0.57      0.47      0.51       152

    accuracy                           1.00    283109
   macro avg       0.89      0.87      0.88    283109
weighted avg       1.00      1.00      1.00    283109



In [63]:
import xgboost as xgb

xgb_base = xgb.XGBClassifier(tree_method = 'gpu_hist',n_estimators=600,max_depth=4,learning_rate=0.5,min_child_weight=1,subsample=1)
xgb_base.fit(X_resampled, y_resampled)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=0, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.5, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=4, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=600,
              n_jobs=0, num_parallel_tree=1, objective='multi:softprob',
              predictor='auto', random_state=0, reg_alpha=0, ...)

In [92]:
print(accuracy_score(xgb_base.predict(X_test),y_test))
print(confusion_matrix(xgb_base.predict(X_test),y_test))
print(classification_report(xgb_base.predict(X_test),y_test))

0.9995620061531071
[[ 44516      0      1      0]
 [     0 172246      0      0]
 [     1      0  66166     67]
 [     0      0     55     57]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     44517
           1       1.00      1.00      1.00    172246
           2       1.00      1.00      1.00     66234
           3       0.46      0.51      0.48       112

    accuracy                           1.00    283109
   macro avg       0.86      0.88      0.87    283109
weighted avg       1.00      1.00      1.00    283109



In [31]:
from sklearn.model_selection import RandomizedSearchCV
estimator = xgb.XGBClassifier(
    objective= 'multi:softprob',
    nthread=6,
    seed=42,
    tree_method = 'gpu_hist'
)

param_test = {'learning_rate' : [0.01, 0.02, 0.03, 0.04, 0.05],
              'n_estimators' : [100, 200, 300, 400, 500, 600, 800, 1000],
              'gamma': [0.5, 1, 1.5, 2, 5],
              'min_child_weight': [1,5,10],
              'subsample': [0.6,0.8,1.0], 
              'max_depth': [1, 2, 3, 4, 5, 6, 7, 9],
              'colsample_bytree': [0.6,0.8,1.0],
              'alpha': [0, 1e-1, 1, 2, 5, 7, 10, 50, 100],
              'lambda': [0, 1e-1, 1, 5, 10, 20, 50, 100]}


random_search = RandomizedSearchCV(
    estimator=estimator,
    param_distributions=param_test,
    n_iter = 10,
    scoring = 'accuracy',
    n_jobs = 6,
    cv = 5,
    verbose=True,
    random_state = 42
)

random_search.fit(X_train, y_train)
opt_parameters_1 =  random_search.best_params_
print(opt_parameters_1)


Fitting 5 folds for each of 10 candidates, totalling 50 fits
{'subsample': 1.0, 'n_estimators': 600, 'min_child_weight': 5, 'max_depth': 3, 'learning_rate': 0.05, 'lambda': 100, 'gamma': 1, 'colsample_bytree': 0.8, 'alpha': 10}


In [32]:
print(random_search.best_score_)

0.9995337466033893


In [85]:
xgb_clf = xgb.XGBClassifier(**{'subsample': 1.0, 'n_estimators': 600, 'min_child_weight': 5, 'max_depth': 3, 'learning_rate': 0.05, 'lambda': 100, 'gamma': 1, 'colsample_bytree': 0.8, 'alpha': 10}
,tree_method='gpu_hist')
xgb_clf.fit(X_resampled,y_resampled)

XGBClassifier(alpha=10, base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=0.8,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=1, gpu_id=0, grow_policy='depthwise',
              importance_type=None, interaction_constraints='', lambda=100,
              learning_rate=0.05, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=3, max_leaves=0, min_child_weight=5,
              missing=nan, monotone_constraints='()', n_estimators=600,
              n_jobs=0, num_parallel_tree=1, objective='multi:softprob',
              predictor='auto', ...)

In [86]:
print(accuracy_score(xgb_clf.predict(X_test),y_test))
print(confusion_matrix(xgb_clf.predict(X_test),y_test))
print(classification_report(xgb_clf.predict(X_test),y_test))

0.9993218159790046
[[ 44511      0      6      0]
 [     0 172246      0      0]
 [     6      0  66047     11]
 [     0      0    169    113]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     44517
           1       1.00      1.00      1.00    172246
           2       1.00      1.00      1.00     66064
           3       0.91      0.40      0.56       282

    accuracy                           1.00    283109
   macro avg       0.98      0.85      0.89    283109
weighted avg       1.00      1.00      1.00    283109



In [69]:
test = pd.read_csv('test_modified.csv')
test

amount_borrowed  term  borrower_rate  installment  org_date_year  \
0                 16000    60         0.1522       382.49           2013   
1                  4800    36         0.2118       181.29           2016   
2                 20000    36         0.1368       680.45           2013   
3                 15000    36         0.1757       539.06           2015   
4                  8000    36         0.1399       273.39           2015   
...                 ...   ...            ...          ...            ...   
104850            18000    60         0.1757       452.89           2015   
104851            20000    36         0.0917       637.58           2015   
104852             5200    36         0.1099       170.22           2015   
104853            20000    36         0.1699       712.96           2015   
104854            16000    36         0.1269       536.72           2015   

        lst_payment_year  pay_period  principal_balance  principal_paid  \
0                   2018        1765             764.42        15235.58   
1                   2018         852            1496.22         3303.78   
2                   2014         304               0.00        20000.00   
3                   2016         397               0.00         4157.47   
4                   2017         608               0.00         8000.00   
...                  ...         ...                ...             ...   
104850              2018        1065            9423.78         8576.22   
104851              2018        1096               0.00        20000.00   
104852              2018         943             828.08         4371.92   
104853              2018         912               0.00        20000.00   
104854              2017         943               0.00        16000.00   

        interest_paid  ...   10   11   12   13   14   15   16   17   18   19  
0             6948.84  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1             1585.40  ...  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
2             2040.69  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
3             2383.13  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4             1399.11  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...               ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
104850        7257.36  ...  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
104851        2942.62  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
104852         914.42  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
104853        5021.26  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
104854        3242.11  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[104855 rows x 32 columns]

In [70]:
from sklearn.metrics import accuracy_score
y_pred = xgb_base.predict(test)


In [71]:
y_pred

array([2, 2, 1, ..., 2, 1, 1], dtype=int64)

In [72]:
preds = le.inverse_transform(y_pred)

In [73]:
preds

array(['CURRENT', 'CURRENT', 'COMPLETED', ..., 'CURRENT', 'COMPLETED',
       'COMPLETED'], dtype=object)

In [74]:
submissions = pd.read_csv('sample_submission.csv')

In [75]:
all_loan_numbers = list(submissions['loan_number'])

In [76]:
submissions["loan_status_description"] = preds

In [77]:
submissions = submissions.reset_index(drop = True)

In [78]:
submissions

loan_number loan_status_description
0           1582834                 CURRENT
1          75679675                 CURRENT
2           6178775               COMPLETED
3          55667318               CHARGEOFF
4          60315522               COMPLETED
...             ...                     ...
104850     56050781                 CURRENT
104851     43769718               COMPLETED
104852     64231414                 CURRENT
104853     59462626               COMPLETED
104854     38455988               COMPLETED

[104855 rows x 2 columns]

In [79]:
submissions.to_csv("p2psubmission_xgb.csv",index=False)